const webpack = require('webpack');
const { merge } = require('webpack-merge');
const baseConfig = require('./webpack.base.babel');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = merge(baseConfig, {
  mode: 'development',
  devtool: 'inline-source-map', // Enable source mapping for better debugging
  devServer: {
    // contentBase: './dist', // Serve static files from the 'dist' directory
    hot: true, // Enable hot module replacement (HMR)
    open: true, // Open the default browser when starting the dev server
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Enable HMR
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: '/app/index.html'
    }),
  ],
});
